### ISSUE TITLE
KeyError on Face_Detection

### ISSUE THREAD

**Issue by fluffykraken** [robmarkcole/HASS-Deepstack#5]
Using v0.4 i get the following error:

```
[homeassistant.helpers.entity] Update for image_processing.face_counter fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/usr/src/app/homeassistant/components/image_processing/__init__.py", line 138, in async_update
    await self.async_process_image(image.content)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/image_processing/deepstack_face.py", line 167, in process_image
    predictions_json = response.json()["predictions"]
KeyError: 'predictions'
```

I'm running HA 85.1

```
My Config:
  - platform: deepstack_face
    ip_address: my_ip
    port: 5000
    scan_interval: 30
    source:
      - entity_id: camera.local_file
        name: face_counter
```

**Comment by robmarkcole** [comment]
I need to be able to reproduce this. To rule out that it is to do with your setup could you setup a `local_file` camera with the `adele_test.jpg` image from the development folder, and try processing that with the component?

**Comment by fluffykraken** [comment]
Same error on the adele_test.jpg.

**Comment by robmarkcole** [comment]
Well that will return `predictions`, so I think it must be an issue with your setup, perhaps port is not accessible?

**Comment by fluffykraken** [comment]
Do you mean the port on HA side or the Deepstack port? The deepstack container seems to get the image..
![image](https://user-images.githubusercontent.com/44376184/51429884-d8df9b00-1c13-11e9-8b61-a4dc0bd8bbd6.png)

**Comment by robmarkcole** [comment]
Deepstack side. Can you confirm you had an earlier release (< 0.4) working?

Well I'm not sure how to reproduce your error. Are you happy to try using python to make a query to the server by [following these instructions](https://deepstackpython.readthedocs.io/en/latest/facerecognition.html#id1)?

**Comment by fluffykraken** [comment]
No, never had a working version before. The object_detection is not working as well so there is something wrong. Will check the link and report back.....

**Comment by fluffykraken** [comment]
I can confirm it is my setup. Same error when using the code from your link....
Thanks for your help!

**Comment by bsmeding** [comment]
Same issue here, the object module works ok but face module give this error

**Comment by itiberiu** [comment]
![image](https://user-images.githubusercontent.com/76488567/214367320-39891e92-a10e-4bff-86f3-8131e6c3b94d.png)
I'm trying to create an automation in hassio using the deeptrack integration and I can't pass this condition. I guess it's a syntax problem but I can't figure it out. In the attributes of the entity, the name is written the same.
 faces:
  - name: Gigi
    confidence: 67.948

ty
